name: myoro_bet_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: '>=3.4.0-79.0.dev <4.0.0'
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  sqlite3_flutter_libs: ^0.5.19
  # path: ^1.9.0
  path: ^1.8.3
  path_provider: ^2.1.2
  window_manager: ^0.3.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true