name: Deploy MyoroBetTracker

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      readme_instructions: ${{ steps.readme_content.outputs.content }}
    steps:
      - name: Read README of v1.0.0 (Grab Installation Instructions)
        id: readme_instructions
        run: echo $(PLEASE)
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: ${{ steps.readme_instructions.outputs.content }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Build Binaries for Linux
        run: echo "Step 2"
  deploy_windows:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Build Binaries for Windows
        run: echo "Step 3"