name: Deploy MyoroBetTracker

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release README
        id: release_readme
        run: |
          git fetch --tags
          git checkout tags\1.0.0+1 -b temp-branch
          echo $(cat README.md)
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: ${{ steps.release_readme.outputs.stdout }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Build Binaries for Linux
        run: echo "Step 2"
  deploy_windows:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Build Binaries for Windows
        run: echo "Step 3"