name: Unit & Widget Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get MyoroBetTracker code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Flutter dependencies
        run: cd myoro_bet_tracker && flutter pub get

      - name: Run tests
        run: cd myoro_bet_tracker && flutter test
